image: node:latest

stages:
  - test
  - production
  
test:
  type: test
  stage: test
  image: node:latest
  script:
    - node -v

production:
  type: deploy
  stage: production
  image: ubuntu:latest
  script:
    - bash ./build.sh