image: node:latest

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: testing-torm
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DB_URI: postgres://postgres:postgres@localhost/testing-torm
  API_PORT: 4000
  JWT_SECRET: sdfjhskjdfhkjhdkjshfskjhdfk

stages:
  - test
  - production

test:
  type: test
  stage: test
  image: node:latest
  script:
    - node -v
    - npm install
    - npm run test

production:
  type: deploy
  stage: production
  image: ubuntu:latest
  script:
    - bash ./build.sh
